flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/BlackBrane/microsoft-translator/
    commit: 958a202b847d019f964b547125755e8b3bc879e6
  extra-dep: true
setup-info:
  ghc:
    windows64:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-unknown-mingw32.tar.xz
        sha1: bdede26c1a2cfcf4ebb08329853d285e32213b3d
        content-length: 175053796
    linux64:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-deb8-linux.tar.xz
        sha1: 3e52527de6f1cad6d7f1c392ddde8148116d4e36
        content-length: 126809836
    macosx:
      8.2.1:
        url: https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-apple-darwin.tar.xz
        sha1: 101405b4fef87a44adf34e48bb63a1a4e945c5c9
        content-length: 114088292
extra-deps:
- StateVar-1.1.0.4
- aeson-1.2.1.0
- ansi-terminal-0.6.3.1
- appar-0.1.4
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.1.0
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-compat-0.9.3
- base-orphans-0.6
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- cabal-doctest-1.0.2
- case-insensitive-1.2.0.10
- cereal-0.5.4.0
- comonad-5.0.1
- conduit-1.2.11
- conduit-extra-1.1.16
- connection-0.2.8
- contravariant-1.4
- cookie-0.4.2.1
- cryptohash-md5-0.11.100.1
- cryptohash-sha1-0.11.100.1
- cryptonite-0.24
- data-default-class-0.1.2.0
- distributive-0.5.2
- dlist-0.8.0.3
- easy-file-0.2.1
- entropy-0.3.8
- exceptions-0.8.3
- expiring-cache-map-0.0.6.1
- fail-4.9.0.0
- fast-logger-2.4.10
- feed-0.3.12.0
- foundation-0.0.13
- generics-sop-0.3.1.0
- hashable-1.2.6.1
- hourglass-0.2.10
- http-api-data-0.3.7.1
- http-client-0.5.7.0
- http-client-tls-0.3.5.1
- http-conduit-2.2.3.2
- http-date-0.0.6.1
- http-media-0.7.0
- http-types-0.9.1
- http2-1.6.3
- integer-logarithms-1.0.2
- iproute-1.7.1
- lifted-base-0.2.3.11
- lucid-2.9.8.1
- memory-0.14.6
- mime-types-0.1.0.7
- mmorph-1.1.0
- monad-control-1.0.2.1
- mono-traversable-1.0.2
- mtl-2.2.1
- nats-1.1.1
- natural-transformation-0.4
- network-2.6.3.2
- network-info-0.2.0.8
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- opaleye-0.5.3.1
- parsec-3.1.11
- pem-0.2.2
- postgresql-libpq-0.9.3.1
- postgresql-simple-0.5.3.0
- primitive-0.6.2.0
- process-1.4.3.0
- product-profunctors-0.8.0.3
- profunctors-5.2
- psqueues-0.2.3.0
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resourcet-1.1.9
- safe-0.3.15
- scientific-0.3.5.1
- scotty-0.11.0
- semigroupoids-5.2
- semigroups-0.18.3
- servant-0.11
- servant-client-0.11
- simple-sendfile-0.2.25
- socks-0.5.5
- split-0.2.3.2
- stm-2.4.4.1
- streaming-commons-0.1.18
- string-conversions-0.4.0.1
- stringsearch-0.3.6.6
- tagged-0.8.5
- tagsoup-0.14.1
- text-1.2.2.2
- th-lift-0.7.7
- th-lift-instances-0.1.11
- time-locale-compat-0.1.1.3
- tls-1.3.11
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unix-time-0.3.7
- unordered-containers-0.2.8.0
- uri-bytestring-0.2.3.3
- utf8-string-1.0.1.1
- uuid-1.3.13
- uuid-types-1.0.3
- vault-0.3.0.7
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- void-0.7.2
- wai-3.2.1.1
- wai-extra-3.0.20.0
- wai-logger-2.3.0
- wai-middleware-static-0.8.1
- warp-3.2.13
- word8-0.1.2
- x509-1.7.1
- x509-store-1.6.3
- x509-system-1.6.5
- x509-validation-1.6.8
- xml-1.3.14
- yaml-0.8.23.3
- zlib-0.6.1.2
- Cabal-2.0.0.2
- aeson-pretty-0.8.5
- hex-0.1.2
- mwc-random-0.13.6.0
- cmdargs-0.10.17
- math-functions-0.2.1.0
- vector-th-unbox-0.2.1.6
compiler-check: match-exact
compiler: ghc-8.2.1
resolver: ghc-8.2.1
