resolver: nightly-2017-08-12
flags: {}
extra-package-dbs: []
packages:
- .
- location:
    git: https://github.com/BlackBrane/microsoft-translator/
    commit: 74c20267c60405a9ffad01edf5215d541ab6778e
  extra-dep: true
extra-deps: []
